site_name: pylibob 文档
repo_url: https://github.com/Herta-villa/pylibob
repo_name: Herta-villa/pylibob
edit_uri: blob/main/docs/
site_description: pylibob -- 另一个 Python LibOneBot
copyright: Copyright &copy; Herta-villa


theme:
  name: material
  language: zh

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 黑暗模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 明亮模式

  custom_dir: docs/.overrides

nav:
  - Code Reference: reference/

markdown_extensions:
  - def_list
  - abbr
  - toc
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs_overrides/.icons
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - social
  - tags
  - literate-nav:
      nav_file: NAV.md
  - gen-files:
      scripts:
        - docs/reference_generator.py
  - mkdocstrings:
      handlers:
          python:
            paths: [src]
            import:
            - https://docs.python.org/zh-cn/3/objects.inv
            - https://docs.aiohttp.org/en/stable/objects.inv
            rendering:
              show_submodules: false
              show_signature_annotations: yes
              separate_signature: yes
              docstring_section_style: list
              line_length: 80
  - section-index

extra:
  social:
    - link: https://onebot.dev
      name: OneBot
      icon: onebot/onebot
